#!/bin/bash
# CC by nc sa Arne Wichmann <arnew@rasentrimmer.org>
#	Karsten Borgwaldt <kb@kb.ccchl.de>
#
# you will need the following: pdflatex, qrencode, bizcard.sty
# look at all places marked with TODO
#
# for basic use fill out these values:
# TODO your phone:
TEL=""
MOBILE=""
# TODO something which gnupg will allow to find your key
LOOKUP=""
# TODO your jabber ID
JABBER=""
# TODO your postal address in two lines
ADDRESS1=""
ADDRESS2=""
# TODO layout of the card
LAYOUT=""

if [ -f "$HOME/.mecard" ]
then
	source "$HOME/.mecard"
fi

# extract info from gpg
GPG="gpg --list-keys --with-fingerprint --with-colons $LOOKUP"
NAME=$($GPG | awk -F: '/@/ {
	for (i=1; i<=NF; ++i)
	{
		if (match($i, "@"))
		{
			name=$i;
			break;
		}
	}
	gsub(" \\(.*", "", name);
	gsub(" <.*", "", name);
	print name;
	exit(0);
}')
MCNAME=`echo $NAME | awk '{ printf("%s,", $NF); for (i=1; i<NF; ++i) { printf("%s ", $i) } }' | sed 's/ $//'`
EMAIL=$($GPG | awk -F: '/@/ {
	for (i=1; i<=NF; ++i)
	{
		if (match($i, "@"))
		{
			email=$i;
			break;
		}
	}
	email=substr(email, index(email, "<") +1);
	print substr(email, 1, length(email) -1);
	exit(0);
}')
HEXFINGERPRINT=`$GPG | grep ^fpr | cut -d: -f 10`
REST=$HEXFINGERPRINT

# chop fingerprint into readable chunks
FINGERPRINT=""
while [ "x" != "x$REST" ];
do
	cutarg="-b -4"
	if [ "x" = "x$FINGERPRINT" ];
	then
		FINGERPRINT=`echo $REST | cut $cutarg `
	else
		FINGERPRINT="$FINGERPRINT\hspace{\stretch{1}}`echo $REST | cut $cutarg `"
	fi
	REST=`echo $REST | cut $cutarg --complement`
done

FINGERPRINT=`echo $FINGERPRINT`

echo name: $NAME
echo fingerprint: $FINGERPRINT
echo hexfingerprint: $HEXFINGERPRINT
echo email: $EMAIL
echo tel: $TEL

# HACK if you want additional info in your MECARD add here
QRSTRING="MECARD:N:$MCNAME;TEL:$(echo $TEL | sed 's/ //g');TEL:$(echo $MOBILE | sed 's/ //g');EMAIL:$EMAIL;ADR:$ADDRESS1,$ADDRESS2;NOTE:$HEXFINGERPRINT;;"
qrencode -m 0 -s 40 -o qr.png "$QRSTRING"

# prepare for LaTeX
latex_escape()
{
	set -x
	local varname="$1"
	export ${varname}=$(eval echo \$$varname | sed 's/_/\\_/g')
	set +x
}

for i in EMAIL JABBER
do
	latex_escape $i
done

case "$LAYOUT" in
	arne)
		B1=( "" "" )
		B2=( "" "" "$MOBILE" "$EMAIL" )
		B3=( "$FINGERPRINT" "" )
	;;
	karsten)
		B1=( "$ADDRESS1" "$ADDRESS2" )
		B2=( "$TEL" "$MOBILE" "$EMAIL" "$JABBER" )
		B3=( "$FINGERPRINT" "" )
	;;
	*)
		: do something funny here
		B3=( "" "You should \_really\_ use a \\\$LAYOUT" )
	;;
esac

# TODO latex generation: change template here
cat > bizcard.tex << EOF
\documentclass[a4paper]{article}

\usepackage[flat]{bizcard}
\usepackage{graphicx}
\usepackage[utf8]{inputenc}

\begin{document}

% 51 x 89 aussen
% 39 x 77 innen 6,6 - 45,83
\begin{bizcard}
  \sffamily

  \put(6,45){\makebox(0,0)[tl]{\includegraphics[height=33mm]{qr.png}}}

  \put(83,45){\makebox(0,0)[tr]{\Large\bfseries{}$NAME}}

  \put(83,35){\makebox(0,0)[tr]{${B1[0]}}}
  \put(83,31){\makebox(0,0)[tr]{${B1[1]}}}

  \put(83,23){\makebox(0,4)[br]{${B2[0]}}}
  \put(83,19){\makebox(0,4)[br]{${B2[1]}}}
  \put(83,15){\makebox(0,4)[br]{${B2[2]}}}
  \put(83,11){\makebox(0,4)[br]{${B2[3]}}}

  \put(6,7){\makebox(77,0)[bl]{\tt\footnotesize{}${B3[0]}}}
  \put(6,3){\makebox(77,0)[bl]{\tt\footnotesize{}${B3[1]}}}

\end{bizcard}

\end{document}
\endinput
EOF

pdflatex bizcard.tex
